- id: 10.1099/acmi.0.000885.v1
  tags:
    - ETEC
    - Malawi
    - Preprint

- id: 10.1016/j.tim.2023.11.001
  image: CFs_review.png
  tags:
    - ETEC virulence factors
    - human and animal
    - review

- id: 10.1128/jcm.00570-23
  image: images/ETECFinder.png
  tags:
    - ETEC virulence factors
    - open science
    - collaboration

- id: 10.1128/msystems.00141-23
  image: images/CS23_bolivia.png

- id: doi:10.1128/mra.00416-22
  image: images/CS13_genome.png

- id: doi:10.1038/s41598-021-88316-2
  image: images/long-read_refs.png
  
- id: doi:10.1080/21505594.2020.1749497
  image: images/CS30_sulfatide.png

- id: doi:10.1371/journal.pone.0209357
  image: images/bacteriphages.png

- id: doi:10.1038/s41598-017-12743-3
  image: images/CS30.png

- id: doi:10.1099/mgen.0.000121
  inage: images/Oag_iguchi.png
  
- id: doi:10.1016/j.ijmm.2016.05.016
  image: images/ST_joffre.png

- id: doi:10.1371/journal.pone.0152899
  image: images/CS6_stability.png
  
- id: doi:10.1002/eji.201445058
  image: images/treg_2015.png
  
- id: doi:10.1038/ng.3145
  image: images/long-read_refs.png


