- id: doi:10.1101/2023.04.11.536449
  type: Preprint
  description: New webtool for predicting ETEC virulence genes, easy and accessible for researchers and clinicians. Multiple new alleles for LT and ST and an unprecedented level of diversity across gene clusters encoding colonization factors.
  date: 2023-04-11
  image: images/ETECFinder.png
  buttons:
    - type: source
      text: Manuscript Source
      link: https://www.biorxiv.org/content/10.1101/2023.04.11.536449v1.abstract
  tags:
    - ETEC virulence factors
    - open science
    - collaboration

- id: doi:10.1101/2023.02.08.527665
  image: images/CS23_bolivia.png

- id: doi:10.1128/mra.00416-22
  image: images/CS13_genome.png

- id: doi:10.1038/s41598-021-88316-2
  image: images/long-read_refs.png
  
- id: doi:10.1080/21505594.2020.1749497
  image: images/CS30_sulfatide.png

- id: doi:10.1371/journal.pone.0209357
  image: images/bacteriphages.png

- id: doi:10.1038/s41598-017-12743-3
  image: images/CS30.png

-id: doi:10.1099/mgen.0.000121
  inage: images/Oag_iguchi.png
  
- id: doi:10.1016/j.ijmm.2016.05.016
  image: images/ST_joffre.png

- id: doi:10.1371/journal.pone.0152899
  image: images/CS6_stability.png
  
- id: doi:10.1002/eji.201445058
  image: images/treg_2015.png
  
- id: doi:10.1038/ng.3145
  image: images/long-read_refs.png


